### ISSUE TITLE
Link to download PDF (maybe as a release for this repo)

### ISSUE THREAD

**Issue by DinisCruz** [trailofbits/ctf#16]
I know that you have the instructions at https://github.com/trailofbits/ctf/issues/6, but it would be easier if the pdf was available for download

Also, any plans to actually put the book for sale?

I for one would prefer to buy the physical copy of the book (which would also be an nice/easy way yo contribute some money to the project)

**Comment by dguido** [comment]
* You're free to submit a PR!
* IMHO you gain more by "working through" the book than "reading" it
* Lots of the content is multimedia - slide decks, videos - none of which take well to printing
