### ISSUE TITLE
Request for solutions or walk-through

### ISSUE THREAD

**Issue by natv** [trailofbits/ctf#25]
First, thank you so much for putting the CTF Field Guide together. I'm just starting to get my feet wet and this looks like an awesome resource.

I wanted to find out if there is (or request) links to solutions for the workshops, as while learning it often helps to validate my answers or get a nudge if I'm completely stuck. I realize these are spoilers so I do think they should be in a separate section so they are not accidentally viewed, but still available somewhere for those who need it.

Nat

**Comment by dguido** [comment]
This repo isn't intended to have a solution guide, but you can find plenty of solved challenges and walkthroughs for them if you search for "ctf writeups" on Github.
