### ISSUE TITLE
[Ed. note: Table to be added/updated later.]

### ISSUE THREAD

**Issue by alanyee** [trailofbits/ctf#26]
This note has there for quite a while. I think the table should be up by now.

**Comment by alanyee** [comment]
I am talking about this here: https://github.com/trailofbits/ctf/blob/master/intro/careers.md

**Comment by dguido** [comment]
You're welcome to make a pull request with an updated list based on the one here:
https://web.archive.org/web/20140228120245/http://pentest.cryptocity.net/careers

**Comment by alanyee** [comment]
Alright, I did it. What do you think?

**Comment by dguido** [comment]
Cool! I checked all the links, and they look like they work and are up to date. Can you remove the link to the old website? I think it's superfluous since everything has been copied here. I will merge it after that.

Thanks!

**Comment by alanyee** [comment]
Alright, I removed the link to the old website.
