### ISSUE TITLE
"WTF is CTF?" section is missing

### ISSUE THREAD

**Issue by awfki** [trailofbits/ctf#28]
This assumes knowledge of what CTF is.  Maybe you're okay with that but I thought I'd point it out.

**Comment by coffeemood** [comment]
I'm sure a simple Google search will suffice

**Comment by awfki** [comment]
Yes, but my point is that you're writing what looks like an introductory book where it's customary to introduce the topic. Also, I just Googled capture the flag and it finds a movie and a game played with colored cloth (which is hella fun when paintball guns are involved). It doesn't have anything about security on the first page and like many people I rarely make it past the first page. (Remember whenwhen you could have 100 results on the first page?)

It's no matter to me, I just thought I'd point that for the sake of completeness and convenience (for the reader) it would be best to make no assumptions and add a paragraph or two about what it is.

**Comment by dguido** [comment]
The [README.md](https://github.com/trailofbits/ctf/blob/master/README.md) includes a brief description of what a CTF is. I'd be happy to accept a pull request if you have a section like the one you imagined to contribute.
