### ISSUE TITLE
easy problem

### ISSUE THREAD

**Issue by Robyn12** [trailofbits/ctf#30]
I made virtualmachine ubuntu and kali inside virtualbox and started program easy32 at ubuntu but my kalis nmap says all ubuntu ports are closed and netcat says connect refused at ubuntu port 12346. I allso installed socat at ubuntu btw.

**Comment by dguido** [comment]
Put down the network scanner and open a disassembler.

**Comment by Robyn12** [comment]
yes ok that was not helpful, but yea i solved it it was misconfigurated virtual network.

**Comment by dguido** [comment]
Ah, my bad. I only ever solve these challenges locally.
